apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculator-adapter
    type: LoadBalancer
  name: calculator-adapter-ext
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31677
  selector:
    app: calculator-adapter
  sessionAffinity: None
